clientID = ''
clientSecret = ''
owner = ''
repo_name = ''
token = ''
melody_owner = ''
melody_repo_name = ''
melody_sub_dir = ''
melody_token = ''
gituser = ''
email = ''
# '/melody' for production, '/melody/static' for local instance (default)
static_url_path = '/melody/static'
